AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway to access Lambda functions

Parameters:
  ProjectName:
    Type: String
    Description: Project name prefix
    Default: MyProject

Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${ProjectName}-AccountAPI"

  ApiResourceView:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: view
      RestApiId: !Ref ApiGatewayRestApi

  ApiResourceUpdate:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: update
      RestApiId: !Ref ApiGatewayRestApi

  ViewMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiResourceView
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: 
          Fn::Sub: 
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ViewLambda.Arn}/invocations
            - ViewLambda:
                Fn::GetAtt: [ ViewLambda, Arn ]

  UpdateMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiResourceUpdate
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Sub:
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateLambda.Arn}/invocations
            - UpdateLambda:
                Fn::GetAtt: [ UpdateLambda, Arn ]

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [ViewMethod, UpdateMethod]
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: dev

  ViewPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ViewLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/GET/view

  UpdatePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UpdateLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/POST/update

Outputs:
  ViewAPIEndpoint:
    Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/view'

  UpdateAPIEndpoint:
    Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/update'
